### ISSUE TITLE
Integrate statistics page

### ISSUE THREAD

**Issue by 2ynn** [LesFruitsDefendus/saskatoon-ng#115]
The statistic panel has not been ported to the new version, we use it to populate our annual review, so it would be good to have it

**Comment by tristanlatr** [comment]
Here is what the statistic page should looks like: 

<img width="1184" alt="saskatoon-statistics" src="https://user-images.githubusercontent.com/19967168/161089255-38576afc-9973-470a-90c1-ffccb92c2006.png">

**Comment by mina-andajos** [comment]
> Here is what the statistic page should looks like: 
> 
> <img width="1184" alt="saskatoon-statistics" src="https://user-images.githubusercontent.com/19967168/161089255-38576afc-9973-470a-90c1-ffccb92c2006.png">
> 
> 

Is this design from the previous saskatoon website?

**Comment by tristanlatr** [comment]
@mina-andajos yes it is.

**Comment by mina-andajos** [comment]
👍
I would like to work on this issue.

**Comment by tristanlatr** [comment]
Thanks @mina-andajos for your enthousiasme. 

You can find the older implementation of the stats view on the `develop` branch of the older Saskatoon repo [here](https://github.com/tiagovaz/saskatoon/blob/e0a522b675594ba72c5aadbf918dd11c22939478/saskatoon/harvest/views.py#L736).

Note that this issue was initially part of the internship itself, because it would probably introduce quite a big diff. But I agree it is not a very complicated task since the older code can be used as a base. But still it could take a longer than expected. If you feel confident you can achieve task in the contribution period, please go ahead.

Talk to you later,

Tristan

**Comment by mina-andajos** [comment]
Yeah I was checking the old code base out. Thanks for pointing out which branch.
