### ISSUE TITLE
Clarify branches and pull requests bases

### ISSUE THREAD

**Issue by 2ynn** [LesFruitsDefendus/saskatoon-ng#167]
@tristanlatr if we are using master branch to target pull requests, what is now the use for the develop branch?

Why not keep on merging pull requests into develop first? When they are tested on dev server we merge them to master.
Then master gets pushed to prod server. And as usual I would still push to prod branch from dev server so we always know what is currently up.
It's confusing now because all we have for new-generation is a "dev" server but I think it will become our production server soon and we have to eventually setup a second one.

Other option is we don't really use a develop branch anymore and just use master, but we still need some sort of a workflow to test things before they are pushed live. I feel keeping the develop branch would be safer, i don't always have time to test branches locally and sometimes i just look at the diffs.

I think it'd be good clarifying this in a CONTRIBUTING.md file

**Comment by mina-andajos** [comment]
Yeah I was wondering the same 💯. Maybe adhering to the [git flow](https://youtu.be/aNJTAYwYIE8) feels like the safest option.

**Comment by tristanlatr** [comment]
Hi,

> It's confusing now because all we have for new-generation is a "dev" server but I think it will become our production server soon and we have to eventually setup a second one.

We should figure out the required DNS changes.

> I feel keeping the develop branch would be safer,

Whatever works, but if we're not targeting pull requests to the main (which is master in our case), is should be indeed clear in the CONTRIBUTING file. Because Github UI targets the PR by default to the main branch. I think sticking to this is best. I'd suggest we update `develop` even to `master` and then make it the main branch. Then PRs created will automatically target the `develop` branch. Then we use `master`, `prod`, `testing`, `qa`  or whatever else for our QA -> Production flow. 

Tell me what you think,

Tristan

**Comment by 2ynn** [comment]
Ok I just made `develop` equal to `master` and set `develop` as default branch in GitHub.
I've also added a rule to prevent direct pushes to the master branch.
I went in most approved pull requests and changed the base branch to develop. I'll merge them shortly.

Thanks for the link @mina-andajos . I think for small fixes we can merge into `develop` and for bigger features we can start dedicated branches (e.g. I will start one for the PublicPropertyForm) so contributors can merge into them before we integrate into develop.

I will start a draft for a CONTRIBUTING.md file.
thanks
