### ISSUE TITLE
Add real tabulation for all list views - Avoid Redis

### ISSUE THREAD

**Issue by tiagovaz** [LesFruitsDefendus/saskatoon-ng#55]
As the database grows, we're getting some import lag on loading the list views.

We currently use a same DRF-based view for delivering both html and json. This has some advantages, but as we get away from Django native views, we start getting trouble integrating to other libraries. That said, I couldn't make a server-side pagination work with our DRF views and filters together with the DataTables js library. It's certainly possible to do, but I just failed so far :-)

I tried playing with native Django pagination. I also tried a few libraries, such as:

- https://github.com/izimobil/django-rest-framework-datatables
- https://github.com/sheikhfaisalanwar/django-rest-framework-datatables-filter

**Comment by tiagovaz** [comment]
Wow that's a big move, thanks @2ynn!

**Comment by tristanlatr** [comment]
Would merging #114 closes this issue ?

**Comment by 2ynn** [comment]
No we are still using Redis server. It's not really a blocker for now

**Comment by mina-andajos** [comment]
@2ynn @tristanlatr I believe we could work on this after merging #340.

I believe what's needed to be done will be:
- Add [limit offset pagination](https://www.django-rest-framework.org/api-guide/pagination/#limitoffsetpagination) (I suggest using this instead of [page number pagination](https://www.django-rest-framework.org/api-guide/pagination/#pagenumberpagination) because users can specify the number of results they want to display with the limit/offset.
- Modify the templates according to the new context the will occur from using pagination:
link example: `http://127.0.0.1:8000/harvest/?season=2022&limit=10&offset=35`
```json
    HTTP 200 OK
{
    "count": 1023,
    "next": "https://api.example.org/accounts/?limit=100&offset=500",
    "previous": "https://api.example.org/accounts/?limit=100&offset=300",
    "results": [
       …
    ]
}
```
- We could modify data table templates in list views.
users could specify a limit:
![image](https://user-images.githubusercontent.com/52796958/180002841-6b5c315a-cdb6-4c1c-b461-79ba544ecf09.png)
we can calculate the number of pages using the offset specified in the url & use `next` and `previous` from the context:
![image](https://user-images.githubusercontent.com/52796958/180003465-c1e8ff9a-13d2-4290-9f40-525c9dfffad6.png)

**Comment by 2ynn** [comment]
as discussed `page_size` query param can be used by default with `PageNumberPagination`.
Otherwise you can subclass it like this:

```
class HarvestPagination(PageNumberPagination):
    page_size = 10
    page_size_query_param = 'page_size'
    max_page_size = REST_FRAMEWORK['PAGE_SIZE']
```
