### ISSUE TITLE
add email field to Person ?

### ISSUE THREAD

**Issue by qusvv** [LesFruitsDefendus/saskatoon-ng#83]
I have noticed many contact persons had an email address registered in the Comments field. Would it make sense to add an email field to the Person model?

**Comment by tristanlatr** [comment]
Thanks for opening this, 

There is also the fact that an email property already exists in the [`member.models.AuthUser`](https://lesfruitsdefendus.github.io/saskatoon-ng/member.models.AuthUser.html) model. 

So we would need to fallback to the `AuthUser`'s property if the `Person` has an account I suppose?

**Comment by tiagovaz** [comment]
> I have noticed many contact persons had an email address registered in the Comments field. Would it make sense to add an email field to the Person model?

Wouldn't this create a confusion given that usernames are necessarily email addresses as well? As I can remember, the current approach is to always create an authuser associated to a Person (that probably answers #84). So that we have the authuser email field as the person email, avoiding two email fields. And if Person has no interest to log-in in the system, we just don't give them such permission on the authuser creation. I think it works like this now. Probably not well documented, so pickleaders are adding email in the comments field, which is no good indeed.

**Comment by qusvv** [comment]
Oh I just meant adding a dedicated, validated email field to the Person model (Blank=True) so pickleaders can add a property owner's email instead of using the comments. 

But yes as Tristan mentioned, if this person gets associated with an auth.user, their email field should match (e.g. when saving the auth.user form?)

**Comment by qusvv** [comment]
Another point related to this is that, as far as i understand, every time a volunteer submits a request for participation a new Person object is created in the database. I assume this leads to duplicates if pickers volunteer more than once. I think it would be nice to have an email field to check if they have participated before (a process that could be similarly applied to property owners). I understand the need to not alter the db model in a way that makes it a headache to migrate... so again I think this has to do with auth groups. I'll look into this more closely.

**Comment by qusvv** [comment]
Ok ok closing this. I initially thought volunteer pickers and owners were only `Person`s and that `AuthUser`s were only created for people who needed to log in (i.e. pick-leaders). Sorry for the confusion, @tiagovaz you actually explained it.

So correct me if I'm wrong:
- << we just don't give them such permission on the authuser creation>> means we don't set a password for them
- pick-leaders are different in that they are registered as staff.
